# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-06 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_Date', models.DateTimeField()),
                ('room_Temperature', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
