# Generated by Django 2.1.5 on 2019-01-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='room_Humidity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
