# Generated by Django 2.1.5 on 2019-02-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190210_0054'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='measurements',
            name='main_app_me_room_Da_0bc272_idx',
        ),
        migrations.AddIndex(
            model_name='measurements',
            index=models.Index(fields=['room_Date'], name='room_Date_idx'),
        ),
    ]
