# Generated by Django 2.1.5 on 2019-02-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20190210_0101'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='measurements',
            name='room_Date_idx',
        ),
    ]
