# Generated by Django 2.1.5 on 2019-03-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20190210_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='room_Humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='room_Light',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='room_Pressure',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='room_Temperature',
            field=models.FloatField(),
        ),
    ]
